# Generated by Django 3.2.7 on 2021-09-25 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('definition', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.TextField()),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch.neighbourhood')),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
    ]
